---
title: 'Network Analysis Workshop: A look into Danish Elite Networks'
author: "Daniel S. Hain (dsh@business.aau.dk)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: show
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}
### Generic preamble
rm(list=ls())
Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

### Knitr options
library(knitr) # For display of the markdown
knitr::opts_chunk$set(warning=FALSE,
                     message=FALSE,
                     comment=FALSE, 
                     fig.align="center"
                     )
```

```{r}
### Load standardpackages
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(magrittr) # For extra-piping operators (eg. %<>%)
```

```{r}
library(tidygraph)
library(ggraph)
```

# Danish elites data

* https://github.com/antongrau/eliter
* https://magtelite.dk/data/

## Get the data

```{r}
# remotes::install_github("antongrau/eliter") # Somehow doesnt work
```

```{r}
data <- read_csv('https://github.com/SDS-AAU/SDS-master/raw/master/00_data/networks/elite_den17.csv') 
```

# First Inspection & EDA

## Initial cleaning

```{r}
data %>% head()
```
```{r}
colnames(data) <- colnames(data) %>% str_to_lower()
```

```{r}
data %>% glimpse()
```

## Selecting categories

```{r}
data %>% count(role, sort = TRUE)
```
```{r}
role_selected <- c('Member', 'Chairman', 'Vice chairman', 'Chief executive')
```

```{r}
data %<>% filter(role %in% role_selected)
```

```{r}
data %>% count(type, sort = TRUE)
```


```{r}
type_select <- c('Organisation')
```

```{r}
data %<>% filter(type %in% type_select)
```


```{r}
data %>% count(person_id, name, sort = TRUE)
```

```{r}
data %>% count(affiliation_id, affiliation, sort = TRUE)
```

```{r}
el <- data %>%
  select(person_id, affiliation_id) %>%
  left_join(data %>% select(person_id, affiliation_id), by = "affiliation_id") 
```

```{r}
el %<>% 
  select(-affiliation_id) %>%
  rename(from = person_id.x, 
         to = person_id.y) %>%
  filter(from != to)
```

```{r}
el %<>%
  count(from, to, name = 'weight') 
```

```{r}
el %>% 
  arrange(desc(weight)) %>%
  head()
```
`
```{r}
el %>% 
  ggplot(aes(x = weight)) +
  geom_histogram()
```

## create the network

Node names

```{r}
nodes <- data %>% select(person_id, name) %>%
  rename(name = person_id, label = name) %>%
  mutate(name = name %>% as.character()) %>%
  distinct(name, .keep_all = TRUE)
```

```{r}
g <- as_tbl_graph(el, directed = FALSE) %>% 
  simplify() %>% 
  as_tbl_graph()
```

```{r}
#g <- g %E>%
#  filter(weight > 1) %N>%
#  filter(!node_is_isolated())
```



```{r}
g
```

```{r}
g <- g %N>% 
  left_join(nodes, by = 'name')
```

```{r}
g
```

```{r}
g %N>%
  mutate(cent_eigen = centrality_eigen(weight = weight)) %>%
  as_tibble() %>%
  arrange(desc(cent_eigen)) %>%
  head()
```

```{r}
g <- g %N>%
  mutate(community = group_louvain(weights = weight) )
```

```{r}
g %N>%
  as_tibble() %>%
  count(community)
```

```{r}
g <- g %N>%
  mutate(community = ifelse(community > 4, NA, community))
```

```{r}
g %N>%
  as_tibble() %>%
  count(community)
```

```{r}
g <- g %N>%
  morph(to_split, community) %N>%
  mutate(cent_com = centrality_eigen(weight = weight),
         com_center = cent_com == max(cent_com)) %>%
  unmorph()
```


```{r, fig.width=15, fig.height=15}
set.seed(1337)
g %E>%
  filter(weight > 1) %N>% 
  filter(percent_rank(centrality_eigen(weights = weight)) > 0.99 ) %>%
  ggraph(layout = 'fr') + 
  geom_edge_link(aes(alpha =  weight)) +
  geom_node_point(aes(size= centrality_eigen(weights = weight), col = community)) +
  geom_node_text(aes(label = label), repel = TRUE) + 
  theme_graph() +
  theme(legend.position = 'bottom')
```

```{r}
g  %N>%
  mutate(cent_drg = centrality_degree(weights = weight)) %>%
  as_tibble() %>%
  arrange(desc(cent_drg)) %>%
  head(50)
```

```{r}
g %N>%
  mutate(cent_dgr = centrality_degree(weights = weight)) %>%
  as_tibble() %>%
  group_by(community) %>%
  arrange(desc(cent_dgr)) %>%
  slice(1:10) %>%
  ungroup()
```

```{r}
g %N>%
  as_tibble() %>%
  group_by(community) %>%
  arrange(desc(cent_com)) %>%
  slice(1:10) %>%
  ungroup()
```

