---
title: "In-Class Exercise: UML & Digital Nomads)"
author: "Daniel S. Hain (dsh@business.aau.dk)"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook:
    code_folding: show
    df_print: paged
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
    theme: flatly
---

```{r setup, include=FALSE}
# Knitr options
### Generic preamble
rm(list=ls()); graphics.off() 
Sys.setenv(LANG = "en") # For english language
options(scipen = 5) # To deactivate annoying scientific number notation

# rm(list=ls()); graphics.off() # get rid of everything in the workspace
if (!require("knitr")) install.packages("knitr"); library(knitr) # For display of the markdown

### Knitr options
knitr::opts_chunk$set(warning=FALSE,
                     message=FALSE,
                     fig.align="center"
                     )
```

# Preamble

## Standard packages

```{r}
### Load packages
library(tidyverse) # Collection of all the good stuff like dplyr, ggplot2 ect.
library(magrittr) # For extra-piping operators (eg. %<>%)
```

## Load data

```{r}
trips <- read_csv('https://sds-aau.github.io/SDS-master/M1/data/trips.csv')
trips %>% glimpse()
```

```{r}
people <- read_csv('https://sds-aau.github.io/SDS-master/M1/data/people.csv')
people %>% glimpse()
```

```{r}
countries <- read_csv( 'https://sds-aau.github.io/SDS-master/M1/data/countrylist.csv')
countries %>% glimpse()
```
```{r}
countries <- read_csv( 'https://sds-aau.github.io/SDS-master/M1/data/countrylist.csv')
countries %>% glimpse()
```

```{r}
cities <- read_csv('https://sds-aau.github.io/SDS-master/M1/data/cities.csv')
cities %>% glimpse()
```

```{r}
# cities <- cities %>%
#   mutate(fragile_states_index = fragile_states_index %>% as.numeric(),
#          peace_score = peace_score %>% as.numeric(),
#          fredom_score = freedom_score %>% as.numeric(),
#          press_freedom_index = press_freedom_index %>% as.numeric())
```

# EDA

```{r}
# Variables for descriptives
vars.desc <- c("cost_nomad", "places_to_work", "freedom_score", "friendly_to_foreigners", "life_score")
```

```{r,warning=FALSE,echo=FALSE}
library(GGally)
```

First, lets look at a classical correlation matrix.

```{r}
ggcorr(cities[,vars.desc], label = TRUE, label_size = 3, label_round = 2, label_alpha = TRUE)
```

# Dimionality Reduction

```{r}
library(FactoMineR)
library(factoextra)
```

```{r}
# cities <- cities %>%
#  select(-X1) %>%
#  drop_na()
```


```{r}
res_pca <- cities %>%
  column_to_rownames('place') %>%
  select_if(is_numeric) %>%
  PCA(scale.unit = TRUE, graph =FALSE)
```


```{r,fig.align='center'}
res_pca %>% 
  fviz_screeplot(addlabels = TRUE, 
                 ncp = 10, 
                 ggtheme = theme_gray())
```


```{r,fig.width=10,fig.height=10,fig.align='center'}
res_pca %>%
  fviz_pca_var(alpha.var = "cos2",
               col.var = "contrib",
               gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
               repel = TRUE) 
```

```{r,,fig.width=15,fig.height=10,fig.align='center'}
res_pca %>%
  fviz_pca_biplot(alpha.ind = "cos2",
                  col.ind = "contrib",
                  gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
                  geom = "point") 
```

# Clustering

```{r,fig.align='center'}
cities %>% 
  drop_na() %>%
  column_to_rownames('place') %>%
  select_if(is_numeric) %>%
  scale() %>%
  fviz_nbclust(hcut, method = "wss")  
```

```{r}
hc <- cities %>%
  select_if(is_numeric) %>%
  hcut(hc_func = "hclust", 
       k = 3, 
       stand = TRUE)
```

```{r}
hc %>%
  glimpse()
```

```{r,,fig.width=15,fig.height=10,fig.align='center'}
hc %>% 
  fviz_cluster(data = cities %>% select_if(is_numeric))  
```

```{r}
hc$cluster
```

```{r}
res_pca %>% 
  glimpse()
```

```{r}
cities[,"cluster"] <- hc$cluster
```

```{r}
cities[,"pca1"] <- res_pca$ind$coord[,1]
cities[,"pca2"] <- res_pca$ind$coord[,2]
```

```{r}
table(cities$cluster, cities$region)
```

```{r}
table(cities$cluster, cities$sub_region)
```

```{r}
cities %>%
  group_by(cluster) %>%
  summarise(pca1 = pca1 %>% mean(),
            pca2 = pca2 %>% mean())
```



```{r}
cities <- cities %>%
  left_join(trips %>% count(place, sort = TRUE, name = 'n_city'), by = 'place')
```

```{r}
cities %>%
  select(place, cluster, n_city) %>%
  group_by(cluster) %>%
  arrange(desc(n_city)) %>%
  slice(1:5) %>%
  ungroup() 
```

To finish up, lets plot it in a map, simplest way possible.

```{r}
geo_merge <- trips %>%
  select(place, longitude, latitude) %>%
  distinct(place, .keep_all = TRUE)
```

```{r}
cities %<>%
  left_join(geo_merge , by = 'place')
```


```{r, fig.height=10, fig.width=15}
library(ggmap)
mapWorld <- borders("world", colour = "gray50", fill = "gray50")
```

```{r}
mapWorld
```


```{r}
mp <- ggplot() +   
  mapWorld 
```

```{r}
mp
```

```{r}
mp + 
  geom_point(data = cities, aes(x = longitude, y = latitude)) +
  scale_colour_discrete()
```

```{r}
mp + 
  stat_density2d(data = trips, 
                 aes(x = longitude, y = latitude, fill = stat(nlevel), col = stat(nlevel) ), 
                 alpha = 0.2, size = 0.2, bins = 10, geom = "polygon") +
  scale_fill_gradient(low = "skyblue", high = "red") +
  scale_color_gradient(low = "skyblue", high = "red")
```




